baseURL = "https://kevinlong.cloud/"
languageCode = "en-us"
title = "A Sofware Engineering, S.R.E. and DevOps blog"
theme = "blackburn"
buildDrafts = true
[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'vs'
    tabWidth = 4